### ISSUE TITLE
Make building spl and zfs more efficient

### ISSUE THREAD

**Issue by dinatale2** [opensfs/lustre-buildbot-config#20]
We can achieve some more efficiency by cloning and tarballing spl and zfs in a similar fashion to how we handle cloning and tarballing lustre. We can generate a tarball for each unique tag we encounter and store it on our buildbot master via FileUpload. When builders need spl/zfs, they can build and install from the tarball to avoid expensive clones.

This would allow us to dynamically change the zfs version (i.e. via commit messages or try builds) in the future.

**Comment by morrone** [comment]
Even more efficient would be to install the pre-build spl/zfs packages in the AMI instead of compiling the same thing over and over and over again.  Why aren't we doing that yet?

Even if we allow changing build dependencies, which we aren't planning to do in the static builders (because they are supposed to be static, and because we can lock down permissions further if we don't need root access to install packages), we don't need to _compile_ zfs in the lustre build farm.  We can build it else where and just select different packages to install.
